# https://taskfile.dev

version: '3'

vars:
  # renovate: datasource=github-releases depName=rafal11ck/gym-api
  API_SPEC_URL: https://github.com/rafal11ck/gym-api/releases/download/v1.12.0/openapi.yaml

tasks:
  api-sdk:
    desc: generate client API SDK
    cmds:
      - npm list orval || npm i
      - curl -sL {{.API_SPEC_URL}} -o openapi.yaml
      - npx -y orval
    silent: true
    preconditions:
      - npm -v
